; Hokkins: обновленная верстка главного меню (27.06.2023)

[MAIN]
item = PICTURE,LOGO
item = FORMATEDTEXT,VERSION
item = SMALLBUTTON,BTN_NEWGAME
item = SMALLBUTTON,BTN_LOAD
item = SMALLBUTTON,BTN_OPTIONS
item = SMALLBUTTON,BTN_CHANGES
item = SMALLBUTTON,BTN_CREDITS
item = SMALLBUTTON,BTN_QUIT
item = TEXTBUTTON2,BTN_BEHANCE
; CHANGES WINDOW
item = 100,FRAME,CHANGES_FRAME_WINDOW
item = 110,FORMATEDTEXT,CHANGES_CAPTION
item = 110,BUTTON,CHANGES_BTN_EXIT
item = 110,FRAME,CHANGES_FRAME
item = 110,FORMATEDTEXT,CHANGES_TEXT
item = 110,SCROLLER,CHANGES_SCROLL
item = WINDOW,CHANGES_WINDOW

[LOGO]
position = 10,20,350,142
groupName = MENU_IDDICTIVE_LOGO
picName = Logo

[VERSION]
command = click,event:OpenBannerURL
command = activate,event:OpenBannerURL
command = deactivate,select:BTN_QUIT
command = upstep,select:BTN_QUIT
command = downstep,select:BTN_NEWGAME
bShowGlowCursor = 0
position = 360,580,790,590
font = INTERFACE_NORMAL
fontScale = 0.8
lineSpace = 10
alignment = right
Color = 255,255,255,255

[BTN_NEWGAME]
command = click,event:NewGamePress
command = activate,event:NewGamePress
command = deactivate,event:NewGamePress
command = upstep,select:VERSION
command = downstep,select:BTN_LOAD
command = leftstep,select:BTN_BEHANCE
command = rightstep,select:VERSION
position = 10,200,330,260
group = MENU_BUTTONS
buttonMiddle = NewGame_unselect
selectButtonMiddle = NewGame_select

[BTN_LOAD]
command = click,event:LoadPress
command = activate,event:LoadPress
command = deactivate,event:LoadPress
command = upstep,select:BTN_NEWGAME
command = downstep,select:BTN_OPTIONS
command = leftstep,select:BTN_BEHANCE
command = rightstep,select:VERSION
position = 10,260,330,320
group = MENU_BUTTONS
buttonMiddle = LoadGame_unselect
selectButtonMiddle = LoadGame_select

[BTN_OPTIONS]
command = click,event:OptionsPress
command = activate,event:OptionsPress
command = deactivate,event:OptionsPress
command = upstep,select:BTN_LOAD
command = downstep,select:BTN_CHANGES
command = leftstep,select:BTN_BEHANCE
command = rightstep,select:VERSION
position = 10,320,330,380
group = MENU_BUTTONS
buttonMiddle = Options_unselect
selectButtonMiddle = Options_select

[BTN_CHANGES]
command = click,select:CHANGES_TEXT,event:ShowChangesWindow
command = activate,select:CHANGES_TEXT,event:ShowChangesWindow
command = deactivate,select:BTN_CHANGES,event:ShowChangesWindow
command = upstep,select:BTN_OPTIONS
command = downstep,select:BTN_CREDITS
command = leftstep,select:BTN_BEHANCE
command = rightstep,select:VERSION
position = 10,380,330,440
group = MENU_BUTTONS
buttonMiddle = Changes_unselect
selectButtonMiddle = Changes_select

[BTN_CREDITS]
command = click,event:CreditsPress
command = activate,event:CreditsPress
command = deactivate,event:CreditsPress
command = upstep,select:BTN_CHANGES
command = downstep,select:BTN_QUIT
command = leftstep,select:BTN_BEHANCE
command = rightstep,select:VERSION
position = 10,440,330,500
group = MENU_BUTTONS
buttonMiddle = Credits_unselect
selectButtonMiddle = Credits_select

[BTN_QUIT]
command = click,event:QuitPress
command = activate,event:QuitPress
command = deactivate,event:QuitPress
command = upstep,select:BTN_CREDITS
command = downstep,select:VERSION
command = leftstep,select:BTN_BEHANCE
command = rightstep,select:VERSION
position = 10,500,330,560
group = MENU_BUTTONS
buttonMiddle = ExitGame_unselect
selectButtonMiddle = ExitGame_select

[BTN_BEHANCE]
command = click,event:OpenBehanceURL
command = activate,event:OpenBehanceURL
command = deactivate,select:BTN_NEWGAME
command = leftstep,select:VERSION
command = rightstep,select:BTN_NEWGAME
command = downstep,select:BTN_NEWGAME
position = 688,4,788,32
string = #Behance
fontScale = 0.75
strOffset = 7
glowoffset = 0,0
pressPictureOffset = 2,2

[CHANGES_WINDOW]
show = 0
nodelist = CHANGES_FRAME_WINDOW,CHANGES_CAPTION,CHANGES_BTN_EXIT
nodelist = CHANGES_FRAME,CHANGES_TEXT,CHANGES_SCROLL

[CHANGES_FRAME_WINDOW]
captionheight = 24
captionimage = piclist=SKILLS, picname=SKILLBORDER, color=(255,128,128,128)
captionoffset = 0,3,0,0
captiondividerheight = 4
position = 960,63,1390,560

[CHANGES_CAPTION]
position = 960,67,1390,87
font = interface_button
fontScale = 1.0
lineSpace = 10
alignment = center
Color = 255,255,255,200

[CHANGES_BTN_EXIT]
position = 1360,67,1380,87
group = ICONS_SPEC
picture = exit button
command = click,event:HideChangesWindow
command = deactivate,event:HideChangesWindow
shadowColor = 0,0,0,0
bShowGlowCursor = 0;
shadowoffset = -1,-1

[CHANGES_FRAME]
position = 970,98,1372,550

[CHANGES_TEXT]
command = click,select:CHANGES_TEXT
command = activate,select:CHANGES_TEXT
command = deactivate,event:HideChangesWindow
command = downstep
command = upstep
command = speeddown
command = speedup
position = 980,108,1362,550
alignment = left
font = interface_normal
fontScale = 0.79
Color = 255,255,255,255
lineSpace = 20
bUseWheel = 1
scrollername = CHANGES_SCROLL
bShowGlowCursor = 0

[CHANGES_SCROLL]
command = click, select:TABLE_LIST
command = deactivate,event:exitCancel
command = downstep
command = upstep
position = 1372,98,1380,550
baseTexture = interfaces\icons.tga
rollerTexture = interfaces\icons.tga
scrollTexPos = 0,0.75,0.045,1.0
rollTexPos = 0.0625,0.875,0.1075,0.96
begEndTexSize = 0.0835
begEndBaseSize = 18
rollerHeight = 18
ownedcontrol = CHANGES_TEXT

