; Native treasurer management; canonical UTF-8 LF source.

[MAIN]
item = 10,PICTURE,MAIN_BACK
item = 15,VIDEORECTANGLE,V_TG
item = 25,SLIDEPICTURE,DUST
;
item = 30,FRAME,MAIN_FRAME
item = 35,FORMATEDTEXT,MAIN_CAPTION
item = 35,BUTTON,EXIT_BTN
;
item = 50,PICTURE,MAIN_CHARACTER_PICTURE
item = 50,PICTURE,OTHER_PICTURE
item = 55,PICTURE,BORDER_PICTURE_1
item = 55,PICTURE,BORDER_PICTURE_2
item = 50,FORMATEDTEXT,CAPACITY
item = 50,FORMATEDTEXT,STORE_CAPACITY
item = 50,SCROLLIMAGE,SHIPS_SCROLL
item = 55,BUTTON,LEFTSCROLLBUTTON
item = 55,BUTTON,RIGHTSCROLLBUTTON
;
item = 50,PICTURE,TAB_BUY
item = 55,FORMATEDTEXT,TAB_BUY_TEXT
item = 50,PICTURE,TAB_SELL
item = 55,FORMATEDTEXT,TAB_SELL_TEXT
item = 50,FORMATEDTEXT,TAB_TOTAL
item = 50,FORMATEDTEXT,SERVICE_STATUS
item = 50,TEXTBUTTON2,RESERVE_BUTTON
item = 50,CHECKBUTTON,AUTO_BUY_CHECK
item = 50,TEXTBUTTON2,EDIT_TARGET_BUTTON
item = 50,TEXTBUTTON2,BUY_NOW_BUTTON
item = 50,TABLE,CHEST_TABLE
item = 55,SCROLLER,SCROLL_CHEST
item = 50,CHECKBUTTON,AUTO_SELL_CHECK
item = 50,CHECKBUTTON,SELL_BLADE_CHECK
item = 50,CHECKBUTTON,SELL_GUN_CHECK
item = 50,CHECKBUTTON,SELL_ARMOR_CHECK
item = 50,CHECKBUTTON,SELL_LOOT_CHECK
item = 50,TEXTBUTTON2,PRICE_LIMIT_BUTTON
item = 50,TEXTBUTTON2,KEEP_COUNT_BUTTON
item = 50,TEXTBUTTON2,KEEP_ITEM_BUTTON
item = 50,TEXTBUTTON2,SELL_NOW_BUTTON
item = 50,TABLE,TABLE_LIST
item = 55,SCROLLER,SCROLL_LIST
;
item = 50,CHECKBUTTON,NOTGOODSTRANSFER_CHECK
item = 50,CHECKBUTTON,BUYCONTRABAND_CHECK
item = 50,TEXTBUTTON2,CLEAR_TABLE_LIST
;
item = WINDOW,BUY_WINDOW
item = WINDOW,SELL_WINDOW
item = WINDOW,MAIN_WINDOW
;
; QTY WINDOW
item = 70,RECTANGLE,QTY_FADER
item = 100,FRAME,QTY_FRAME
item = 150,FORMATEDTEXT,QTY_WINDOW_FIX
item = 150,FORMATEDTEXT,QTY_CAPTION
item = 150,PICTURE,QTY_PICTURE
item = 150,FORMATEDTEXT,QTY_INFO
item = 150,FORMATEDTEXT,QTY_RULE_INFO
item = 150,FORMATEDTEXT,QTY_RESULT
item = 145,VIDEO,V_QTY_EDIT
item = 150,PCEDITBOX,QTY_EDIT
item = 150,BUTTON,QTY_REMOVE_ALL_BUTTON
item = 150,BUTTON,QTY_REMOVE_BUTTON
item = 150,BUTTON,QTY_ADD_BUTTON
item = 150,BUTTON,QTY_ADD_ALL_BUTTON
item = 150,TEXTBUTTON2,QTY_OK_BUTTON
item = 150,TEXTBUTTON2,QTY_CANCEL_BUTTON
item = WINDOW,QTY_WINDOW
;
start = TABLE_LIST

[MAIN_BACK]
bAbsoluteRectangle = 0
position = -134,0,933,600
textureName = interfaces\sith\bgr_goodstransfer.tga

[V_TG]
bAbsoluteRectangle = 5
position = -1,-1,1440,853
color = 255,128,128,128

[DUST]
position 	= -200,-300,1000,1000
techniqueName	= iRotate
textureName	= interfaces\sith\dust.tga
textureRect	= 0,0,1.0,1.0
color		= 200,200,200,200
rotate		= -0.03,0.005
speed		= 6000,0.0,0

[MAIN_FRAME]
captionheight = 24
captionimage = piclist=SITH_ICONS, picname=frame caption red, color=(255,128,128,128)
position = 100,10,700,590
backimage = piclist=SITH_PAPIRUS, picname=papirus, color=(190,128,128,128)

[MAIN_CAPTION]
position = 100,14,700,34
font = interface_button
fontScale = 1.0
lineSpace = 10
alignment = center
Color = 255,255,255,200
string = titleGoodsTransfer

[EXIT_BTN]
position = 675,13,695,33
group = ICONS_SPEC
picture = exit button
command = click,event:exitCancel
command = deactivate,event:exitCancel
shadowColor = 0,0,0,0
bShowGlowCursor = 0;
shadowoffset = -1,-1

[MAIN_CHARACTER_PICTURE]
position = 110,44,165,99
textureName = interfaces\portraits\128\face_1.tga

[OTHER_PICTURE]
position =  635,44,690,99
textureName = interfaces\store.tga

[BORDER_PICTURE_1]
textureName = interfaces\emptyborder.tga
position = 110,44,165,99

[BORDER_PICTURE_2]
textureName = interfaces\emptyborder.tga
position = 635,44,690,99

[CAPACITY]
position = 165,44,255,99
fontScale = 0.85
lineSpace = 16
alignment = center
Color = 255,255,255,255

[STORE_CAPACITY]
position = 545,44,635,99
fontScale = 0.85
lineSpace = 16
alignment = center
Color = 255,255,255,255

[SHIPS_SCROLL]
command = activate
command = deactivate,event:ExitCancel
command = upstep,select:TABLE_LIST
command = downstep,select:TABLE_LIST
command = rightstep
command = leftstep
command = speedright
command = speedleft
command = click,select:SHIPS_SCROLL
position = 255,44,545,99
imageSize = 55,55
wDelta = 3
glowoffset = 0,0

[LEFTSCROLLBUTTON]
command = activate,select:SHIPS_SCROLL,com:speedleft:SHIPS_SCROLL
command = click,select:SHIPS_SCROLL,com:leftstep:SHIPS_SCROLL,com:activate:LEFTSCROLLBUTTON
position = 340,49,375,94
group = ICONS
picture = left arrow
pressPictureOffset = 1,1
shadowOffset = 1,1
pressShadowOffset = 0,0
pressDelay = 10

[RIGHTSCROLLBUTTON]
command = activate,select:SHIPS_SCROLL,com:speedright:SHIPS_SCROLL
command = click,select:SHIPS_SCROLL,com:rightstep:SHIPS_SCROLL,com:activate:RIGHTSCROLLBUTTON
position = 425,49,460,94
group = ICONS
picture = right arrow
pressPictureOffset = 1,1
shadowOffset = 1,1
pressShadowOffset = 0,0
pressDelay = 10

[TABLE_LIST]
command = deactivate,event:exitCancel
command = click,select:TABLE_LIST
command = dblclick
command = activate
command = upstep
command = downstep
command = rightstep,event:ADD
command = leftstep,event:REMOVE
command = speedright,event:ADD_ALL
command = speedleft,event:REMOVE_ALL
position = 100,202,690,503
scroller = SCROLL_LIST
vlinewidth = 1
hlineheight = 1
borderwidth = 1
rowquantity = 10
colquantity = 7
fontcellvalignment = center
colswidth = 60,60,60,224,60,65,60
rowsheight = 40,29,29,29,29,29,29,29,29,29
NormalLineHeight = 29

[SCROLL_LIST]
command = click, select:TABLE_LIST
command = deactivate,event:exitCancel
command = downstep
command = upstep
position = 690,202,700,503
ownedcontrol = TABLE_LIST

[NOTGOODSTRANSFER_CHECK]
command = activate
command = click
command = deactivate,event:exitCancel
position = 300,178,480,194
alignment = left
iconsize = 14,14
rect_textoffset = 25,0,0,0
individualpos = 1
section1 = 0,0,NotGoodsTransfer
fontScale = 0.8
textClickable = 1
bShowGlowCursor = 0

[BUYCONTRABAND_CHECK]
command = activate
command = click
command = deactivate,event:exitCancel
position = 490,178,690,194
alignment = left
iconsize = 14,14
rect_textoffset = 25,0,0,0
individualpos = 1
section1 = 0,0,BuyContraband
fontScale = 0.8
textClickable = 1
bShowGlowCursor = 0

[CLEAR_TABLE_LIST]
command = activate
command = click
command = deactivate,event:exitCancel
command = upstep,select:TABLE_LIST
position = 415,532,555,557
string = ClearList
font = interface_normal
fontScale = 0.85
strOffset = 6
glowoffset = 0,0

[QTY_WINDOW]
show = 0
active = 0
nodelist = QTY_FADER,QTY_FRAME,QTY_CAPTION,QTY_PICTURE,QTY_INFO,QTY_RULE_INFO,QTY_RESULT,QTY_WINDOW_FIX,QTY_EDIT,V_QTY_EDIT
nodelist = QTY_REMOVE_ALL_BUTTON,QTY_REMOVE_BUTTON,QTY_ADD_BUTTON,QTY_ADD_ALL_BUTTON,QTY_OK_BUTTON,QTY_CANCEL_BUTTON

[QTY_FADER]
bAbsoluteRectangle = 5
position = -1,-1,800,600
leftColor = 200,0,0,0
topColor = 200,0,0,0
rightColor = 200,0,0,0
bottomColor = 200,0,0,0
borderColor = 0,0,0,0

[QTY_FRAME]
position = 200,200,600,500
backimage = piclist=SITH_PAPIRUS, picname=papirus, color=(255,150,150,150)
captionheight = 24
captionimage = piclist=SITH_ICONS, picname=frame caption red, color=(255,128,128,128)
captiondividerheight = 1

[QTY_CAPTION]
position = 200,204,600,224
font = interface_button
fontScale = 1.1
lineSpace = 10
alignment = center
Color = 255,255,255,200

[QTY_PICTURE]
position = 210,240,290,320
textureName = interfaces\store_64.tga
bShowGlowCursor = 0

[QTY_INFO]
position = 300,240,590,400
fontScale = 0.9
lineSpace = 16
alignment = center

[QTY_WINDOW_FIX]
command = click,event:None
command = activate,event:None
position = 200,200,600,500

[V_QTY_EDIT]
bAbsoluteRectangle = 0
position = 315,430,485,455
sTexture = bigbutton
color = 120,60,80,70

[QTY_EDIT]
command = click,select:QTY_EDIT
command = deactivate,event:UnShowWindow
command = activate,event:confirmChangeQTY_EDIT
position = 323,430,477,457
strFont = interface_button
argbFontColor = 255,255,255,255
stringLength = 9
stringWidth = 170
stringalign = center
stringoffset = 9,3
MiddleImage = color=(0,128,128,128), piclist=MAIN_ICONS, picname=middle side button
excludechars = qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM ёйцукенгшщзхъфывапролджэячсмитьбю	ЁЙЦУКЕНГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮ!@#№$%^&*()_-+=~`'"|\/?:;<>,.{}[]

[QTY_REMOVE_ALL_BUTTON]
command = click,event:REMOVE_ALL
command = activate,event:REMOVE_ALL
command = deactivate,event:UnShowWindow
;command = rclick
group = ARROWS
picture = left_all
position = 251,430,276,455
disableColor = 255,128,128,128
shadowOffset = 3,2

[QTY_REMOVE_BUTTON]
command = click,event:REMOVE
command = activate,event:REMOVE
command = deactivate,event:UnShowWindow
;command = rclick
group = ARROWS
picture = left
position = 279,430,304,455
disableColor = 255,128,128,128
shadowOffset = 3,2

[QTY_ADD_BUTTON]
command = click,event:ADD
command = activate,event:ADD
command = deactivate,event:UnShowWindow
;command = rclick
group = ARROWS
picture = right
position = 497,430,522,455
disableColor = 255,128,128,128
shadowOffset = 3,2

[QTY_ADD_ALL_BUTTON]
command = click,event:ADD_ALL
command = activate,event:ADD_ALL
command = deactivate,event:UnShowWindow
group = ARROWS
picture = right_all
position = 525,430,550,455
disableColor = 255,128,128,128
shadowOffset = 3,2

[QTY_OK_BUTTON]
command = activate
command = click
command = deactivate,event:UnShowWindow
command = rightstep,event:ADD
command = leftstep,event:REMOVE
command = speedright,event:ADD_ALL
command = speedleft,event:REMOVE_ALL
position = 288,465,388,490
string = Ok
font = interface_normal
fontScale = 0.85
strOffset = 6
glowoffset = 0,0

[QTY_CANCEL_BUTTON]
command = activate
command = click
command = deactivate,event:UnShowWindow
command = rightstep,event:ADD
command = leftstep,event:REMOVE
command = speedright,event:ADD_ALL
command = speedleft,event:REMOVE_ALL
position = 419,465,519,490
string = Cancel
font = interface_normal
fontScale = 0.85
strOffset = 6
glowoffset = 0,0

[MAIN_WINDOW]
nodelist = EXIT_BTN,MAIN_CAPTION,MAIN_CHARACTER_PICTURE,OTHER_PICTURE,BORDER_PICTURE_1,BORDER_PICTURE_2,CAPACITY,STORE_CAPACITY
nodelist = SHIPS_SCROLL,LEFTSCROLLBUTTON,RIGHTSCROLLBUTTON,TAB_BUY,TAB_BUY_TEXT,TAB_SELL,TAB_SELL_TEXT,TAB_TOTAL,RESERVE_BUTTON,SERVICE_STATUS
nodelist = BUY_WINDOW,SELL_WINDOW

[BUY_WINDOW]
nodelist = TABLE_LIST,SCROLL_LIST,AUTO_BUY_CHECK,NOTGOODSTRANSFER_CHECK,BUYCONTRABAND_CHECK,EDIT_TARGET_BUTTON,CLEAR_TABLE_LIST,BUY_NOW_BUTTON

[SELL_WINDOW]
show = 0
active = 0
nodelist = CHEST_TABLE,SCROLL_CHEST,AUTO_SELL_CHECK,SELL_BLADE_CHECK,SELL_GUN_CHECK,SELL_ARMOR_CHECK
nodelist = PRICE_LIMIT_BUTTON,KEEP_COUNT_BUTTON,KEEP_ITEM_BUTTON,SELL_NOW_BUTTON,SELL_LOOT_CHECK

[TAB_BUY]
command = deactivate,event:exitCancel
command = click,event:eTabControlPress
command = activate,event:eTabControlPress
command = rightstep,select:TAB_SELL
command = downstep,select:TABLE_LIST
command = upstep,select:SHIPS_SCROLL
position = 110,116,395,141
groupName = TABS
picName = TabDeSelected
bShowGlowCursor = 0

[TAB_BUY_TEXT]
position = 110,116,395,141
fontScale = 0.85
lineSpace = 12
alignment = center
valignment = 1

[TAB_SELL]
command = deactivate,event:exitCancel
command = click,event:eTabControlPress
command = activate,event:eTabControlPress
command = leftstep,select:TAB_BUY
command = downstep,select:CHEST_TABLE
command = upstep,select:SHIPS_SCROLL
position = 405,116,690,141
groupName = TABS
picName = TabSelected
bShowGlowCursor = 0

[TAB_SELL_TEXT]
position = 405,116,690,141
fontScale = 0.85
lineSpace = 12
alignment = center
valignment = 1

[TAB_TOTAL]
position = 110,510,690,527
fontScale = 0.85
lineSpace = 14
alignment = left

[SERVICE_STATUS]
position = 110,558,690,586
fontScale = 0.75
lineSpace = 12
alignment = left

[CHEST_TABLE]
command = deactivate,event:exitCancel
command = click,select:CHEST_TABLE
command = dblclick
command = upstep
command = downstep
position = 100,202,690,503
scroller = SCROLL_CHEST
vlinewidth = 1
hlineheight = 1
borderwidth = 1
rowquantity = 10
colquantity = 6
fontcellvalignment = center
colswidth = 50,210,50,55,75,149
rowsheight = 40,29,29,29,29,29,29,29,29,29
NormalLineHeight = 29

[SCROLL_CHEST]
command = click,select:CHEST_TABLE
command = deactivate,event:exitCancel
command = downstep
command = upstep
position = 690,202,700,503
ownedcontrol = CHEST_TABLE

[QTY_RULE_INFO]
position = 210,240,590,400
fontScale = 0.9
lineSpace = 16
alignment = center

[QTY_RESULT]
position = 210,406,590,424
fontScale = 0.85
lineSpace = 14
alignment = center

[EDIT_TARGET_BUTTON]
command = activate
command = click
command = deactivate,event:exitCancel
command = upstep,select:TABLE_LIST
position = 280,532,405,557
font = interface_normal
fontScale = 0.85
strOffset = 6
glowoffset = 0,0

[BUY_NOW_BUTTON]
command = activate
command = click
command = deactivate,event:exitCancel
command = upstep,select:TABLE_LIST
position = 565,532,690,557
font = interface_normal
fontScale = 0.85
strOffset = 6
glowoffset = 0,0

[KEEP_ITEM_BUTTON]
command = activate
command = click
command = deactivate,event:exitCancel
command = upstep,select:CHEST_TABLE
position = 280,532,510,557
font = interface_normal
fontScale = 0.85
strOffset = 6
glowoffset = 0,0

[SELL_NOW_BUTTON]
command = activate
command = click
command = deactivate,event:exitCancel
command = upstep,select:CHEST_TABLE
position = 520,532,690,557
font = interface_normal
fontScale = 0.85
strOffset = 6
glowoffset = 0,0

[RESERVE_BUTTON]
command = activate
command = click
command = deactivate,event:exitCancel
command = upstep,select:TAB_BUY
position = 110,532,270,557
font = interface_normal
fontScale = 0.85
strOffset = 6
glowoffset = 0,0

[PRICE_LIMIT_BUTTON]
command = activate
command = click
command = deactivate,event:exitCancel
command = upstep,select:CHEST_TABLE
position = 110,146,370,171
font = interface_normal
fontScale = 0.85
strOffset = 6
glowoffset = 0,0

[KEEP_COUNT_BUTTON]
command = activate
command = click
command = deactivate,event:exitCancel
command = upstep,select:CHEST_TABLE
position = 380,146,530,171
font = interface_normal
fontScale = 0.85
strOffset = 6
glowoffset = 0,0

[AUTO_BUY_CHECK]
command = activate
command = click
command = deactivate,event:exitCancel
command = downstep,select:TABLE_LIST
position = 110,178,290,194
alignment = left
iconsize = 14,14
rect_textoffset = 25,0,0,0
individualpos = 1
section1 = 0,0,All
fontScale = 0.8
textClickable = 1
bShowGlowCursor = 0

[AUTO_SELL_CHECK]
command = activate
command = click
command = deactivate,event:exitCancel
command = downstep,select:CHEST_TABLE
position = 540,150,690,166
alignment = left
iconsize = 14,14
rect_textoffset = 25,0,0,0
individualpos = 1
section1 = 0,0,All
fontScale = 0.8
textClickable = 1
bShowGlowCursor = 0

[SELL_BLADE_CHECK]
command = activate
command = click
command = deactivate,event:exitCancel
command = downstep,select:CHEST_TABLE
position = 110,178,250,194
alignment = left
iconsize = 14,14
rect_textoffset = 25,0,0,0
individualpos = 1
section1 = 0,0,All
fontScale = 0.8
textClickable = 1
bShowGlowCursor = 0

[SELL_GUN_CHECK]
command = activate
command = click
command = deactivate,event:exitCancel
command = downstep,select:CHEST_TABLE
position = 255,178,425,194
alignment = left
iconsize = 14,14
rect_textoffset = 25,0,0,0
individualpos = 1
section1 = 0,0,All
fontScale = 0.8
textClickable = 1
bShowGlowCursor = 0

[SELL_ARMOR_CHECK]
command = activate
command = click
command = deactivate,event:exitCancel
command = downstep,select:CHEST_TABLE
position = 430,178,550,194
alignment = left
iconsize = 14,14
rect_textoffset = 25,0,0,0
individualpos = 1
section1 = 0,0,All
fontScale = 0.8
textClickable = 1
bShowGlowCursor = 0

[SELL_LOOT_CHECK]
command = activate
command = click
command = deactivate,event:exitCancel
command = downstep,select:CHEST_TABLE
position = 555,178,690,194
alignment = left
iconsize = 14,14
rect_textoffset = 25,0,0,0
individualpos = 1
section1 = 0,0,All
fontScale = 0.8
textClickable = 1
bShowGlowCursor = 0
