;
; Sith Интерфейс "Торговля"
;

[MAIN]
item = 10,PICTURE,MAIN_BACK
item = 10,SLIDEPICTURE,DUST
item = 20,VIDEORECTANGLE,V_TRADEBOOK
item = 20,TITLE,TITLE
item = 20,pc,BUTTON,EXIT_BTN

; boal new menu -->
item = 200,BUTTON,I_CHARACTER_2
item = 200,BUTTON,I_SHIP_2
item = 200,BUTTON,I_QUESTBOOK_2
item = 200,BUTTON,I_NATIONS_2
item = 200,BUTTON,I_ITEMS_2
item = 100,pc,BUTTON,I_CHARACTER
item = 100,pc,BUTTON,I_SHIP
item = 100,pc,BUTTON,I_QUESTBOOK
item = 100,pc,BUTTON,I_NATIONS
item = 100,pc,BUTTON,I_ITEMS
item = 100,STRINGCOLLECTION,STR_BUTTONS
item = 202,FRAME,BACK_FRAME
item = 210,TEXTBUTTON2,MODE_TOGGLE
item = 210,TEXTBUTTON2,PIN_CITY
item = 210,TEXTBUTTON2,CONTRABAND_TOGGLE
item = 210,FORMATEDTEXT,TRADE_ROUTE
item = 200,TABLE,TABLE_CITY
item = 201,SCROLLER,SCROLL_CITY
item = 200,TABLE,TABLE_GOODS
item = 201,SCROLLER,SCROLL_GOODS

[MAIN_BACK]
bAbsoluteRectangle = 0
position = -134,0,933,600
textureName = interfaces\sith\bgr_tradebook.tga

; анимация на заднем фоне
[DUST]
position 	= -200,-300,1000,1000
techniqueName	= iRotate
textureName	= interfaces\sith\dust.tga
textureRect	= 0,0,1.0,1.0
color		= 200,200,200,200
rotate		= -0.03,0.005
speed		= 6000,0.0,0

[V_TRADEBOOK]
bAbsoluteRectangle = 5
position = -1,-1,1440,853
color = 255,128,128,128

[TITLE]
position = 0,50,800,85
stringOffset = 6
stringWidth = 220

[EXIT_BTN]
position = 770,59,790,77
group = ICONS_SPEC
picture = exit button
command = click,event:exitCancel
shadowColor = 0,0,0,0


; top menu
[STR_BUTTONS]
string = buttonCharacter,font:INTERFACE_TITLE,pos:{60,20},fc:{255,255,255,255},bc:{0,128,128,128},scale:0.7,state:{S}
string = buttonShip,font:INTERFACE_TITLE,pos:{240,20},fc:{255,255,255,255},bc:{0,128,128,128},scale:0.7,state:{S}
string = buttonQuestBook,font:INTERFACE_TITLE,pos:{415,20},fc:{255,255,255,255},bc:{0,128,128,128},scale:0.7,state:{S}
string = buttonNation,font:INTERFACE_TITLE,pos:{580,20},fc:{255,255,255,255},bc:{0,128,128,128},scale:0.7,state:{S}
string = Sel Items,font:INTERFACE_TITLE,pos:{727,20},fc:{255,255,255,255},bc:{0,128,128,128},scale:0.7,state:{S}

[I_CHARACTER]
bBreakCommand = 1
command = click
command = deactivate,event:exitCancel
group = ICONS_SPEC
picture = pers button
position = 0,5,50,55
shadowColor = 90,0,0,0

[I_CHARACTER_2]
bBreakCommand = 1
command = click
position = 50,5,175,55

[I_SHIP]
bBreakCommand = 1
command = click
group = ICONS_SPEC
picture = ship button
position = 180,5,230,55
shadowColor = 90,0,0,0
command = deactivate,event:exitCancel

[I_SHIP_2]
bBreakCommand = 1
command = click
position = 230,5,340,55

[I_QUESTBOOK]
bBreakCommand = 1
command = click
command = deactivate,event:exitCancel
group = ICONS_SPEC
picture = questbook button
position = 355,5,405,55
shadowColor = 90,0,0,0

[I_QUESTBOOK_2]
bBreakCommand = 1
command = click
position = 405,5,510,55

[I_NATIONS]
bBreakCommand = 1
command = click
command = deactivate,event:exitCancel
group = ICONS_SPEC
picture = nations button
position = 510,5,560,55
shadowColor = 90,0,0,0

[I_NATIONS_2]
bBreakCommand = 1
command = click
position = 560,5,660,55

[I_ITEMS]
bBreakCommand = 1
command = click
command = deactivate,event:exitCancel
group = ICONS_SPEC
picture = items button
position = 665,5,715,50
shadowColor = 90,0,0,0

[I_ITEMS_2]
bBreakCommand = 1
command = click
position = 727,5,800,55

[BACK_FRAME]
position = 10,85,776,570
backimage = piclist=SITH_TABLE, picname=top shadow, color=(0,128,128,128)
lefttop_size		= 10,10
righttop_size		= 10,10
leftbottom_size		= 10,10
rightbottom_size	= 10,10

[MODE_TOGGLE]
command = click
command = activate
command = deactivate,event:exitCancel
position = 20,86,110,112
string = Ok
fontScale = 0.68
glowoffset = 0,0

[PIN_CITY]
command = click
command = activate
command = rclick,select:PIN_CITY,event:ShowInfoWindow
command = deactivate,event:exitCancel
position = 114,86,202,112
string = Ok
fontScale = 0.68
glowoffset = 0,0

[CONTRABAND_TOGGLE]
command = click
command = activate
command = rclick,select:CONTRABAND_TOGGLE,event:ShowInfoWindow
command = deactivate,event:exitCancel
position = 206,86,316,112
string = Ok
fontScale = 0.55
glowoffset = 0,0

[TRADE_ROUTE]
position = 330,86,770,112
fontScale = 0.72
lineSpace = 12
valignment = 1
font = interface_button
alignment = center
Color = 255,255,255,255

[TABLE_CITY]
command = deactivate,event:exitCancel
command = click,select:TABLE_CITY
command = upstep
command = downstep
position = 10,115,320,570
backimage = piclist=SITH_TABLE, picname=left side, color=(225,128,128,128)
scroller = SCROLL_CITY
rowquantity = 15
colquantity = 4
vlinewidth = 1
hlineheight = 1
headerlineheight = 1
borderwidth = 0
bordercornersize = 0,0
fontcellvalignment = center
colswidth = 35,100,100,75
rowsheight = 35,30,30,30,30,30,30,30,30,30,30,30,30,30,30
NormalLineHeight = 30

[SCROLL_CITY]
command = click, select:TABLE_CITY
command = deactivate,event:exitCancel
command = downstep
command = upstep
position = 316,115,330,570
ownedcontrol = TABLE_CITY

[TABLE_GOODS]
command = deactivate,event:exitCancel
command = click,select:TABLE_GOODS
command = rclick,select:TABLE_GOODS,event:ShowInfoWindow
command = upstep
command = downstep
position = 330,115,780,570
backimage = piclist=SITH_TABLE, picname=right side, color=(225,128,128,128)
scroller = SCROLL_GOODS
rowquantity = 15
colquantity = 7
vlinewidth = 1
hlineheight = 1
headerlineheight = 1
borderwidth = 0
bordercornersize = 0,0
fontcellvalignment = center
colswidth = 118,22,55,55,60,60,80
rowsheight = 35,30,30,30,30,30,30,30,30,30,30,30,30,30,30
NormalLineHeight = 30

[SCROLL_GOODS]
command = click, select:TABLE_GOODS
command = deactivate,event:exitCancel
command = downstep
command = upstep
position = 776,115,790,570
ownedcontrol = TABLE_GOODS